name: Generate Meta Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"  # Runs daily at 2am AWST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests requests-oauthlib

      - name: Generate feed from BrickLink
        run: python generate_feed.py
        env:
          BL_CONSUMER_KEY: ${{ secrets.BL_CONSUMER_KEY }}
          BL_CONSUMER_SECRET: ${{ secrets.BL_CONSUMER_SECRET }}
          BL_TOKEN_VALUE: ${{ secrets.BL_TOKEN_VALUE }}
          BL_TOKEN_SECRET: ${{ secrets.BL_TOKEN_SECRET }}

      - name: Commit and push feed to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add meta_product_feed.csv index.html || true
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "🚀 Auto-update Facebook feed"
          git push origin main
