name: Scrape BrickLink Categories

on:
  workflow_dispatch:
  schedule:
    - cron: '18 18 * * *' # 2am AWST daily

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: category_scraper
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium

      - name: Run scraper
        run: python scrape_categories.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/categories.csv
          git commit -m "Update BrickLink category list" || echo "No changes"
          git push
